name: Cloud Android 11 Phone (Win11 + Tailscale + RDP)

on:
  workflow_dispatch:

jobs:
  android-phone:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # ---------------- Tailscale ----------------
      - name: Install Tailscale
        run: |
          curl -L https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -o tailscale-installer.exe
          Start-Process ".\tailscale-installer.exe" -ArgumentList "/quiet" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" version
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TS_KEY }} --hostname github-cloudphone --accept-routes --accept-dns

      # ---------------- Java ----------------
      - name: Install Java
        run: choco install microsoft-openjdk11 -y

      # ---------------- Android Command Line Tools ----------------
      - name: Download Android Command Line Tools
        run: |
          curl -L https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip -o cmd-tools.zip
          if (!(Test-Path "C:\Android")) { mkdir C:\Android }
          if (!(Test-Path "C:\Android\cmdline-tools\latest")) { mkdir C:\Android\cmdline-tools\latest }
          tar -xf cmd-tools.zip -C C:\Android\cmdline-tools\latest

      # ---------------- Install SDK & Emulator ----------------
      - name: Install Android 11 SDK & system images
        run: |
          & "C:\Android\cmdline-tools\latest\bin\sdkmanager.bat" --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator" --verbose

      - name: Create Android 11 AVD
        run: |
          & "C:\Android\cmdline-tools\latest\bin\avdmanager.bat" create avd -n cloudphone -k "system-images;android-30;google_apis;x86_64" --device "pixel" --force

      - name: Launch Android Emulator (headless)
        run: |
          & "C:\Android\emulator\emulator.exe" -avd cloudphone -no-window -no-audio -no-snapshot &

      # ---------------- Enable RDP ----------------
      - name: Enable RDP
        run: |
          net user runneradmin MyStrongPassword123! /add
          net localgroup administrators runneradmin /add
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      # ---------------- Keep Alive ----------------
      - name: Keep Alive
        run: |
          echo "Cloud Android Phone is running..."
          ping -t 127.0.0.1 > NUL
